### ISSUE TITLE
package not found in composer

### ISSUE THREAD

**Issue by MR4online** [iCalcreator/UrlRsrc#1]
Hi,

when I try to install this package like documented:

`composer require kigkonsult/urlrsrc:dev-master`

I get the following error:

`    - Root composer.json requires kigkonsult/urlrsrc, it could not be found in any version, there may be a typo in the package name.`

do you mean?:

`composer require kigkonsult/http:dev-master`
kigkonsult/http

https://packagist.org/packages/kigkonsult/http

**Comment by iCalcreator** [comment]
Fixed in packagist
