### ISSUE TITLE
PHP8 Fatal TypeError

### ISSUE THREAD

**Issue by MR4online** [iCalcreator/UrlRsrc#2]
I try to load an ICS file with the newest version of your libaries and PHP 8.3.13

```
 "kigkonsult/icalcreator": "v2.41.90",
 "kigkonsult/http": "1.1",
```

Code:

```
use Kigkonsult\Icalcreator\Vcalendar;
use Kigkonsult\Http\UrlRsrc;

$v = new Vcalendar();
$iCalContent = UrlRsrc::getContent($link);
$v->parse($iCalContent);
```
I get the following Error:

`Fatal error: Uncaught TypeError: Kigkonsult\Http\UrlRsrc::getContent(): Return value must be of type string, true returned in /var/www/html/html/vendor/kigkonsult/http/src/UrlRsrc.php:169`

**Comment by iCalcreator** [comment]
Try the new 1.2 (master) release
